set VM=cuckoo1
 
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiBIOSReleaseDate "12/17/2012"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiBIOSReleaseMajor "1"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiBIOSReleaseMinor "19"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiBIOSVendor "FUJITSU // American Megatrends Inc."
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiBIOSVersion "V4.6.5.3 R1.19.0 for D3162-A1x"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiBoardAssetTag "                      "
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiBoardBoardType "10"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiBoardLocInChass "                      "
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiBoardProduct "D3162-A1"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiBoardSerial "34BF1C06"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiBoardVendor "FUJITSU"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiBoardVersion "S26361-D3162-A1"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiChassisAssetTag "                                        "
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiChassisSerial "A1B4909FF9"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiChassisType "6"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiChassisVendor "FUJITSU"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiChassisVersion "C$PXW4"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiProcManufacturer "Intel(R) Corporation"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiProcVersion "Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiSystemFamily "Not Specified"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiSystemProduct "ESPRIMO P910"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiSystemSKU "S26361-Kxxx-Vyyy"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiSystemSerial "BC59F9EA5D"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiSystemUuid "4A6692B9-FB38-4EAC-86D9-E415C78BB29E"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiSystemVendor "FUJITSU"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/pcbios/0/Config/DmiSystemVersion "string:"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/piix3ide/0/Config/PrimaryMaster/ModelNumber "ST1000DM003-1CH162"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/piix3ide/0/Config/PrimaryMaster/SerialNumber "474F58C1"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/piix3ide/0/Config/PrimaryMaster/FirmwareRevision "CC45"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/piix3ide/0/Config/SecondaryMaster/ATAPIVendorId "HL-DT-ST"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/piix3ide/0/Config/SecondaryMaster/ATAPIRevision "TF03"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/piix3ide/0/Config/SecondaryMaster/ATAPIProductId "DVDRAM GHA2N"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/piix3ide/0/Config/SecondaryMaster/ATAPISerialNumber "D045F2C24CF"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/acpi/0/Config/CustomTable "C:%HOMEPATH%\VirtualBox VMs\%VM%\ESPRIMOP910_DSDT.bin"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/acpi/0/Config/AcpiOemId "FTS"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/acpi/0/Config/AcpiCreatorId "INTL"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/Devices/acpi/0/Config/AcpiCreatorRev "20091112"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/CPUM/HostCPUID/00000001/ecx "0x57982203"	
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/CPUM/HostCPUID/80000002/eax "0x65746e49"	
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/CPUM/HostCPUID/80000002/ebx "0x2952286c"	
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/CPUM/HostCPUID/80000002/ecx "0x726f4320"	
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/CPUM/HostCPUID/80000002/edx "0x4d542865"	
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/CPUM/HostCPUID/80000003/eax "0x37692029"	
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/CPUM/HostCPUID/80000003/ebx "0x3737332d"	
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/CPUM/HostCPUID/80000003/ecx "0x50432030"	
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/CPUM/HostCPUID/80000003/edx "0x20402055"	
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/CPUM/HostCPUID/80000004/eax "0x30342e33"	
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/CPUM/HostCPUID/80000004/ebx "0x207a4847"	
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/CPUM/HostCPUID/80000004/ecx "0x20202020"	
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata %VM% VBoxInternal/CPUM/HostCPUID/80000004/edx "0x00202020"
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" modifyvm %VM% --macaddress1	"001999e4a6d1"
