#!/bin/bash

if [ $# -eq 0 ] ; then
  echo "[*] Please add vm name!"
  echo "[*] Available vms:"
  /usr/bin/VBoxManage list vms | awk -F'"' {' print $2 '} | sed 's/"//g'
  exit 1
fi

if [ ! -f "${HOME}/VirtualBox VMs/${VM}/ESPRIMOP910_DSDT.bin" ] ; then
	echo "[*] Please copy ESPRIMOP910_DSDT.bin to ${HOME}/VirtualBox VMs/${VM}/ first!"
	exit 1
fi

/usr/bin/VBoxManage setextradata "${VM}" VBoxInternal/Devices/acpi/0/Config/CustomTable "${HOME}/VirtualBox VMs/${VM}/ESPRIMOP910_DSDT.bin"

exit 0
