@echo off

rem Most lines were generated by:
rem   https://github.com/nsmfoo/antivmdetection

if -%1-==-- (
  echo "[*] Please provide VM to modify:"
  "C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" list vms
  exit /b
)

"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" showvminfo "%~1" > nul 2>&1
if %ERRORLEVEL% neq 0 (
  echo "[*] VM %~1 does not exist"
  exit /b
)

if not exist "C:%HOMEPATH%\VirtualBox VMs\%~1\ESPRIMOP910_DSDT.bin" (
  echo "[*] Please copy ESPRIMOP910_DSDT.bin to C:%HOMEPATH%\VirtualBox VMs\%~1 first!"
  exit /b
)

set VM="%~1"

"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" setextradata "%VM%" "VBoxInternal/Devices/acpi/0/Config/CustomTable" "%HOMEPATH%/VirtualBox VMs/%VM%/ESPRIMOP910_DSDT.bin"

exit 0
